version: "3"

services:

  hotpot:
    image: victorskl/hotpot:0.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./secrets.json:/etc/hotpot/secrets.json
    env_file: .env
    restart: always
