version: "3"

services:

  mongodb:
    image: mongo:3.6.5
    ports:
      - "27017:27017"
      - "3000:3000"
    volumes:
      - /mnt/mongo/db:/data/db
      - /mnt/mongo/configdb:/data/configdb
    container_name: mongodb
    restart: always

  nabemono:
    image: nabemono:latest
    depends_on:
      - mongodb
    network_mode: "service:mongodb"
    restart: always

