version: "3"

services:

  mongodb:
    image: mongo:3.6.5
    ports:
      - "27017:27017"
      - "3000:3000"
    volumes:
      - ./mongo/db:/data/db
    container_name: mongodb
    restart: always

  hotpot:
    image: hotpot:latest
    volumes:
      - ./secrets.json:/etc/hotpot/secrets.json
    depends_on:
      - mongodb
    network_mode: "service:mongodb"
    restart: always

